<?php
/**
 * Inicialización del Sistema
 * Horchata Mexican Food - Sistema de Pedidos
 */

// Iniciar sesión si no está iniciada
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Configuración de idiomas
define('DEFAULT_LANGUAGE', 'es');
define('SUPPORTED_LANGUAGES', ['en', 'es']);

// Función para detectar país por IP
function detectCountryByIP($ip = null) {
    if ($ip === null) {
        $ip = $_SERVER['REMOTE_ADDR'] ?? '';
        
        // Si está detrás de un proxy, intentar obtener la IP real
        if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
            $ips = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
            $ip = trim($ips[0]);
        } elseif (!empty($_SERVER['HTTP_X_REAL_IP'])) {
            $ip = $_SERVER['HTTP_X_REAL_IP'];
        }
    }
    
    // Si la IP es localhost, devolver un país por defecto
    if ($ip === '127.0.0.1' || $ip === '::1' || empty($ip)) {
        return DEFAULT_LANGUAGE === 'es' ? 'MX' : 'US';
    }
    
    try {
        // Usar ipapi.co para detectar el país
        $response = @file_get_contents("https://ipapi.co/{$ip}/country_code/");
        if ($response !== false) {
            return trim($response);
        }
    } catch (Exception $e) {
        error_log("Error detecting country by IP: " . $e->getMessage());
    }
    
    // Valor por defecto
    return DEFAULT_LANGUAGE === 'es' ? 'MX' : 'US';
}

// Función para obtener idioma basado en país
function getLanguageByCountry($country) {
    // Países que usan español (prioridad)
    $spanish_countries = ['MX', 'ES', 'AR', 'CO', 'CL', 'PE', 'VE', 'EC', 'GT', 'CU', 'BO', 'DO', 'HN', 'PY', 'SV', 'NI', 'CR', 'PA', 'UY', 'PY', 'GQ'];
    
    // Países que usan inglés
    $english_countries = ['US', 'CA', 'GB', 'IE', 'AU', 'NZ', 'ZA', 'SG', 'MY', 'PH', 'IN'];
    
    if (in_array($country, $spanish_countries)) {
        return 'es';
    } elseif (in_array($country, $english_countries)) {
        return 'en';
    }
    
    // Por defecto, usar español
    return 'es';
}

// Procesar cambio de idioma
if (isset($_GET['lang']) && in_array($_GET['lang'], SUPPORTED_LANGUAGES)) {
    $_SESSION['language'] = $_GET['lang'];
    // Guardar que el usuario cambió manualmente el idioma
    $_SESSION['language_manual'] = true;
    // No redirigir automáticamente para evitar bucles de refresh
}

// Establecer idioma por defecto si no está definido
if (!isset($_SESSION['language'])) {
    // Si no hay cambio manual, detectar país
    if (!isset($_SESSION['language_manual'])) {
        $country = detectCountryByIP();
        $detected_lang = getLanguageByCountry($country);
        $_SESSION['language'] = $detected_lang;
        error_log("Auto-detected language: $detected_lang for country: $country");
    } else {
        $_SESSION['language'] = DEFAULT_LANGUAGE;
    }
}

// Función para obtener el idioma actual
function getCurrentLanguage() {
    return $_SESSION['language'] ?? DEFAULT_LANGUAGE;
}

// Función para obtener texto traducido
function __($key, $default = '') {
    $lang = getCurrentLanguage();
    
    // Textos en español
    $texts_es = [
        'home' => 'Inicio',
        'menu' => 'Menú',
        'reviews' => 'Reseñas',
        'contact' => 'Contacto',
        'cart' => 'Carrito',
        'language' => 'Idioma',
        'spanish' => 'Español',
        'english' => 'English',
        'welcome' => 'Bienvenido a Horchata Mexican Food',
        'authentic_mexican' => 'Auténtica Comida Mexicana',
        'our_specialties' => 'Nuestras Especialidades',
        'our_categories' => 'Nuestras Categorías',
        'customer_reviews' => 'Reseñas de Clientes',
        'contact_info' => 'Información de Contacto',
        'business_hours' => 'Horarios de Atención',
        'address' => 'Dirección',
        'phone' => 'Teléfono',
        'email' => 'Correo',
        'monday_saturday' => 'Lunes - Sábado',
        'sunday' => 'Domingo',
        'add_to_cart' => 'Agregar al Carrito',
        'view_menu' => 'Ver Menú',
        'read_reviews' => 'Leer Reseñas',
        'contact_us' => 'Contáctanos',
        'order_now' => 'Ordenar Ahora',
        'learn_more' => 'Conocer Más',
        'get_directions' => 'Obtener Direcciones',
        'call_now' => 'Llamar Ahora',
        'send_message' => 'Enviar Mensaje',
        'follow_us' => 'Síguenos',
        'all_rights_reserved' => 'Todos los derechos reservados',
        'terms_conditions' => 'Términos y Condiciones',
        'privacy_policy' => 'Política de Privacidad',
        'accessibility' => 'Accesibilidad',
        // Hero Section
        'authentic_cooking' => 'Auténtica Cocina Mexicana',
        'flavors_conquer' => 'Sabores que Conquistan el Corazón',
        'discover_magic' => 'Descubre la magia de la cocina mexicana tradicional con ingredientes frescos, recetas auténticas y el sabor que solo Horchata Mexican Food puede ofrecerte.',
        'years' => 'Años',
        'clients' => 'Clientes',
        'dishes' => 'Platillos',
        'explore_menu' => 'Explorar Menú',
        'specialties' => 'Especialidades',
        'spicy' => 'Picante',
        'fresh' => 'Fresco',
        'made_with_love' => 'Hecho con Amor',
        // About Section
        'our_story' => 'Nuestra Historia',
        'since_2015' => 'Desde 2015, Horchata Mexican Food ha sido el hogar de la auténtica cocina mexicana en nuestra comunidad.',
        'fresh_ingredients' => 'Utilizamos ingredientes frescos y recetas tradicionales que han sido transmitidas de generación en generación. Cada platillo es preparado con amor y dedicación para brindarte una experiencia culinaria única.',
        'years_experience' => 'Años de experiencia',
        'satisfied_clients' => 'Clientes satisfechos',
        // Categories Section
        'categories' => 'Categorías',
        'explore_variety' => 'Explora la variedad de sabores auténticos que tenemos para ofrecerte',
        // Reviews Section
        'testimonials' => 'Testimonios',
        'what_customers_say' => 'Lo que Dicen Nuestros Clientes',
        'verified_reviews' => 'Reseñas verificadas de clientes que han disfrutado de nuestros platillos auténticos',
        'see_all_reviews' => 'Ver Todas las Reseñas',
        // Contact Section
        'contact_us_title' => 'Contáctanos',
        'we_are_here' => 'Estamos aquí para servirte. ¡Visítanos o haz tu pedido!',
        'location' => 'Ubicación',
        'hours' => 'Horarios',
        'phone_number' => '+1 (310) 204-2659',
        'address_full' => '10814 Jefferson Blvd<br>Culver City, CA',
        'hours_full' => 'Lun-Sáb: 8:30 AM - 9:00 PM<br>Domingo: 9:00 AM - 8:00 PM',
        // Loading texts
        'loading_specialties' => 'Preparando los mejores sabores para ti',
        'loading_categories' => 'Organizando nuestros sabores para ti',
        'loading_testimonials' => 'Recopilando las mejores experiencias',
        'explore_full_menu' => 'Explorar Menú Completo',
        // Menu Page
        'our_menu' => 'Nuestro Menú',
        'discover_authentic' => 'Descubre la auténtica cocina mexicana con nuestros platillos tradicionales, preparados con ingredientes frescos y recetas familiares.',
        'all_categories' => 'Todos',
        'search_dishes' => 'Buscar platillos...',
        'preparing_menu' => 'Preparando tu menú...',
        'loading_delicious' => 'Cargando nuestros deliciosos platillos',
        'oops_not_found' => '¡Ups! No encontramos ese platillo',
        'no_dishes_found' => 'No se encontraron platillos con esos términos. Intenta con otros ingredientes o explora nuestras categorías.',
        'clear_search' => 'Limpiar Búsqueda',
        'view_all_categories' => 'Ver Todas las Categorías',
        'spicy_dishes' => 'Platillos Picantes',
        'spicy_description' => 'Nuestros platillos más picantes para los amantes del chile',
        'fresh_ingredients_title' => 'Ingredientes Frescos',
        'fresh_ingredients_description' => 'Utilizamos solo los ingredientes más frescos y de calidad',
        'made_with_love_title' => 'Hecho con Amor',
        'made_with_love_description' => 'Cada platillo se prepara con el amor de nuestras recetas familiares',
        // Additional translations
        'popular_dishes_description' => 'Los platillos más populares de nuestro menú, preparados con amor y tradición mexicana',
        'footer_description' => 'Auténtica comida mexicana preparada con ingredientes frescos y recetas tradicionales. Disfruta de nuestros sabores únicos con servicio pickup.',
        'quick_links' => 'Enlaces Rápidos',
        'contact_info' => 'Información de Contacto',
        'business_hours' => 'Horarios de Atención',
        'monday_saturday' => 'Lunes - Sábado',
        'sunday' => 'Domingo',
        'all_rights_reserved' => 'Todos los derechos reservados',
        'terms_conditions' => 'Términos y Condiciones',
        'accessibility' => 'Accesibilidad',
        'your_cart' => 'Tu Carrito',
        'cart_empty' => 'Tu carrito está vacío',
        'total' => 'Total',
        'proceed_payment' => 'Proceder al Pago',
        // Reviews Public Page
        'what_customers_say_reviews' => 'Lo que Dicen Nuestros Clientes',
        'discover_authentic_experiences' => 'Descubre las experiencias auténticas de nuestros clientes y únete a la comunidad de amantes de la comida mexicana tradicional.',
        'site_reviews' => 'Reseñas del Sitio',
        'yelp_reviews' => 'Reseñas de Yelp',
        'loading_reviews' => 'Cargando reseñas...',
        'collecting_best_experiences' => 'Recopilando las mejores experiencias',
        'yelp_reviews_title' => 'Reseñas en Yelp',
        'see_all_yelp_reviews' => 'Ve todas nuestras reseñas y calificaciones en Yelp',
        'yelp_widget' => 'Widget de Yelp',
        'yelp_widget_description' => 'Aquí se mostrará el widget oficial de Yelp con las reseñas más recientes.',
        'view_on_yelp' => 'Ver en Yelp',
        'load_widget' => 'Cargar Widget',
        'average_rating' => 'Calificación Promedio',
        'total_reviews' => 'Reseñas Totales',
        'satisfied_customers' => 'Clientes Satisfechos',
        'happy_customers' => 'Clientes Felices',
        'share_experience' => '¿Tienes una Experiencia que Compartir?',
        'share_experience_description' => 'Si has visitado nuestro restaurante, nos encantaría conocer tu opinión. Tu feedback nos ayuda a mejorar y servir mejor a nuestra comunidad.',
        'review_on_yelp' => 'Reseñar en Yelp',
        'contact_us' => 'Contactarnos',
        // Terms and Conditions Page
        'terms_conditions_title' => 'Términos y Condiciones',
        'terms_intro' => 'El sitio web de Horchata Mexican Food es únicamente para fines informativos y no realiza ventas en línea. Todos los derechos de propiedad intelectual están protegidos, y no nos hacemos responsables por errores en la información publicada.',
        'website_use' => 'Uso del Sitio Web',
        'website_use_description' => 'Este sitio es únicamente para fines informativos. No aceptamos pedidos en línea ni realizamos ventas a través de esta plataforma.',
        'intellectual_property' => 'Propiedad Intelectual',
        'intellectual_property_description' => 'Todo el contenido de este sitio, incluyendo texto, imágenes y logos, es propiedad de Horchata Mexican Food.',
        'disclaimer' => 'Exención de Responsabilidad',
        'disclaimer_description' => 'Horchata Mexican Food no se hace responsable por errores en la información del sitio o por daños derivados de su uso.',
        'contact_information' => 'Información de Contacto',
        // Accessibility Page
        'accessibility_title' => 'Accesibilidad WCAG',
        'accessibility_intro' => 'Horchata Mexican Food se compromete a hacer su sitio web accesible para todas las personas, incluyendo aquellas con discapacidades.',
        'our_commitment' => 'Nuestro Compromiso',
        'our_commitment_description' => 'Creemos que la accesibilidad web es fundamental para crear una experiencia inclusiva para todos nuestros visitantes. Nos esforzamos por cumplir con las pautas de accesibilidad web (WCAG) para garantizar que nuestro sitio sea utilizable por personas con diversas capacidades.',
        'measures_implemented' => 'Medidas Implementadas',
        'adequate_color_contrast' => 'Contraste de Colores Adecuado',
        'adequate_color_contrast_description' => 'Utilizamos combinaciones de colores que cumplen con los estándares de contraste WCAG AA para garantizar la legibilidad.',
        'alt_text_images' => 'Texto Alternativo para Imágenes',
        'alt_text_images_description' => 'Todas las imágenes incluyen descripciones alternativas (alt text) para usuarios de lectores de pantalla.',
        'screen_reader_navigation' => 'Navegación Compatible con Lectores de Pantalla',
        'screen_reader_navigation_description' => 'Nuestro sitio está estructurado para ser completamente navegable usando tecnologías de asistencia.',
        'responsive_design' => 'Diseño Responsivo',
        'responsive_design_description' => 'El sitio se adapta a diferentes tamaños de pantalla y dispositivos para una experiencia óptima.',
        'additional_features' => 'Características Adicionales',
        'semantic_html5' => 'Estructura semántica HTML5 para mejor navegación',
        'descriptive_links' => 'Enlaces descriptivos y claros',
        'accessible_forms' => 'Formularios accesibles con etiquetas apropiadas',
        'keyboard_navigation' => 'Navegación por teclado completa',
        'scalable_text' => 'Texto escalable sin pérdida de funcionalidad',
        'hierarchical_content' => 'Contenido organizado jerárquicamente',
        'report_accessibility_issues' => 'Reportar Problemas de Accesibilidad',
        'report_accessibility_description' => 'Si experimentas dificultades para acceder a cualquier parte de nuestro sitio web, o si tienes sugerencias para mejorar la accesibilidad, por favor contáctanos:',
        // Product Detail Page
        'quantity' => 'Cantidad',
        'ingredients' => 'Ingredientes',
        'nutritional_information' => 'Información Nutricional',
        'preparation_time' => 'Tiempo de preparación',
        'spicy_level' => 'Nivel de picante',
        'preparation_time_default' => 'Tiempo de preparación: 15-20 min',
        'spicy_level_default' => 'Nivel de picante: Medio',
        'traditional_recipe' => 'Receta tradicional',
        'ingredients_description' => 'Ingredientes frescos seleccionados cuidadosamente para garantizar la mejor calidad y sabor auténtico.',
        'fresh_ingredients_list_1' => 'Carne de res premium',
        'fresh_ingredients_list_2' => 'Cebolla y ajo frescos',
        'fresh_ingredients_list_3' => 'Especias tradicionales',
        'fresh_ingredients_list_4' => 'Tortillas de maíz',
        'nutritional_info_default' => 'La información nutricional detallada no está disponible para este producto.',
        'favorites' => 'Favoritos',
        'related_products' => 'Productos Relacionados',
        'related_products_description' => 'Otros platillos de la misma categoría que podrían interesarte',
        'view' => 'Ver',
        // Customize Modal
        'customize_order' => 'Personalizar Pedido',
        'special_instructions' => 'Instrucciones Especiales',
        'special_instructions_placeholder' => 'Ej: Sin cebolla, sin tomate, sin cilantro...',
        'special_instructions_help' => 'Agrega cualquier instrucción especial para tu pedido',
        'extras' => 'Extras',
        'extra_cheese' => 'Queso Extra',
        'extra_guacamole' => 'Guacamole Extra',
        'extra_sour_cream' => 'Crema Agria Extra',
        'spice_level' => 'Nivel de Picante',
        'mild' => 'Suave',
        'hot' => 'Picante',
        'extra_hot' => 'Extra Picante',
        'cancel' => 'Cancelar',
        // Checkout Page
        'finish_order' => 'Finalizar Pedido',
        'customer_information' => 'Información del Cliente',
        'first_name' => 'Nombre',
        'last_name' => 'Apellido',
        'email_address' => 'Correo Electrónico',
        'phone_number' => 'Teléfono',
        'pickup_information' => 'Información de Pickup',
        'pickup_date' => 'Fecha de Pickup',
        'pickup_time' => 'Hora de Pickup',
        'select_time' => 'Seleccionar hora',
        'allergies_modifications' => 'Alergias, modificaciones, etc.',
        'payment_method' => 'Método de Pago',
        'pay_safely_paypal' => 'Paga de forma segura con PayPal',
        'pay_on_pickup' => 'Pagar al Recoger',
        'cash_card_paypal_pickup' => 'Efectivo, tarjeta o PayPal al recoger',
        'order_summary' => 'Resumen del Pedido',
        'quantity' => 'Cantidad',
        'subtotal' => 'Subtotal',
        'tax' => 'Impuestos',
        'tax_percentage' => 'Impuestos (8.25%)',
        'total' => 'Total',
        'confirm_order' => 'Confirmar Pedido',
        'ssl_protected' => 'Tu información está protegida con encriptación SSL',
        'processing' => 'Procesando...',
        'complete_all_fields' => 'Por favor, completa todos los campos requeridos',
        'please_complete_required_fields' => 'Por favor completa todos los campos requeridos',
        'complete_customer_and_pickup_info' => 'Completa la información del cliente y la información de recogida antes de proceder al pago',
        'error_processing_order' => 'Error al procesar el pedido: ',
        // Wire Transfer
        'wire_transfer' => 'Transferencia Bancaria',
        'wire_transfer_description' => 'Realiza una transferencia bancaria directa',
        'wire_transfer_information' => 'Información para Transferencia Bancaria',
        'bank_name' => 'Nombre del Banco',
        'account_holder' => 'Titular de la Cuenta',
        'account_number' => 'Número de Cuenta',
        'routing_number_wire' => 'Número de Ruteo (Wire Transfer)',
        'routing_number_direct_deposit' => 'Número de Ruteo (Depósito Directo)',
        'swift_code' => 'Código SWIFT',
        'wire_transfer_instructions' => 'Instrucciones',
        'for_direct_deposit' => 'Para depósitos directos',
        'for_international_wires' => 'Para transferencias internacionales',
        'wire_transfer_note' => 'Por favor incluye el número de pedido en la descripción de la transferencia para facilitar la identificación.',
        'important' => 'Importante',
        // Order Success Page
        'order_confirmed' => 'Pedido Confirmado',
        'order_confirmed_message' => 'Gracias por tu pedido. Te hemos enviado un correo de confirmación con todos los detalles.',
        'order_details' => 'Detalles del Pedido',
        'order_number' => 'Número de Pedido',
        'order_date' => 'Fecha de Pedido',
        'order_items' => 'Items del Pedido',
        'payment_information' => 'Información de Pago',
        'payment_method' => 'Método de Pago',
        'payment_status' => 'Estado del Pago',
        'pay_on_pickup' => 'Pagar al Recoger',
        'contact_information' => 'Información de Contacto',
        'phone' => 'Teléfono',
        'email' => 'Correo',
        'address' => 'Dirección',
        'back_to_home' => 'Volver al Inicio',
        'view_menu' => 'Ver Menú',
        'print_order' => 'Imprimir Pedido',
        'leave_review' => 'Deja una Reseña',
        'leave_review_message' => '¡Nos encantaría saber qué te pareció tu experiencia! Deja una reseña y ayuda a otros clientes.',
        'write_review' => 'Escribir Reseña',
        // Review Form
        'rating' => 'Calificación',
        'select_rating' => 'Selecciona una calificación',
        'stars' => 'estrellas',
        'star' => 'estrella',
        'your_review' => 'Tu Reseña',
        'write_your_review_here' => 'Escribe tu reseña aquí...',
        'submit_review' => 'Enviar Reseña',
        // Review error messages
        'error_loading_reviews' => 'Error al cargar reseñas',
        'error_loading_public_reviews' => 'Error al cargar las reseñas públicas',
        'try_again' => 'Intentar de nuevo',
        // Additional order success translations
        'qr_code_for_restaurant' => 'Código QR para el Restaurante',
        'scan_qr_to_view_order' => 'Escanea este código para ver el pedido en el sistema',
        'customer' => 'Cliente',
        'status' => 'Estado',
        'subtotal' => 'Subtotal',
        'tax' => 'Impuestos',
        'quantity' => 'Cantidad',
        // Product customization extras
        'guacamole' => 'Guacamole',
        'sour_cream' => 'Crema',
        'cheese' => 'Queso',
        // Extras Management
        'extras_management' => 'Gestión de Extras',
        'add_extra' => 'Agregar Extra',
        'edit_extra' => 'Editar Extra',
        'extras_list' => 'Lista de Extras',
        'assign_extras_to_products' => 'Asignar Extras a Productos',
        'select_product' => 'Seleccionar Producto',
        'available_extras' => 'Extras Disponibles',
        'select_product_first' => 'Selecciona un producto primero',
        'no_category' => 'Sin categoría',
        'confirm_delete_extra' => '¿Estás seguro de que quieres eliminar este extra?',
        // Admin Panel
        'dashboard' => 'Dashboard',
        'products' => 'Productos',
        'orders' => 'Pedidos',
        'qr_scanner' => 'QR Scanner',
        'reports' => 'Reportes',
        'categories' => 'Categorías',
        'extras' => 'Extras',
        'users' => 'Usuarios',
        'profile' => 'Perfil',
        'view_site' => 'Ver Sitio',
        'logout' => 'Cerrar Sesión',
        // Product Management
        'new_product' => 'Nuevo Producto',
        'edit_product' => 'Editar Producto',
        'name_english' => 'Nombre (Inglés)',
        'name_spanish' => 'Nombre (Español)',
        'category' => 'Categoría',
        'select_category' => 'Seleccionar categoría',
        'price' => 'Precio',
        'description_english' => 'Descripción (Inglés)',
        'description_spanish' => 'Descripción (Español)',
        'available' => 'Disponible',
        'featured' => 'Destacado',
        'product_image' => 'Imagen del Producto',
        'preview' => 'Vista previa',
        'image_formats' => 'Formatos: JPG, PNG, GIF. Máximo 5MB',
        'product_extras' => 'Extras del Producto',
        'available_extras' => 'Extras Disponibles',
        'assigned_extras' => 'Extras Asignados',
        'loading_extras' => 'Cargando extras',
        'loading_assigned_extras' => 'Cargando extras asignados',
        'add_new_extra' => 'Agregar Nuevo Extra',
        'cancel' => 'Cancelar',
        'create_product' => 'Crear Producto',
        'update_product' => 'Actualizar Producto',
        // Order Management
        'order_management' => 'Gestión de Pedidos',
        'refresh' => 'Actualizar',
        'print' => 'Imprimir',
        'pending' => 'Pendiente',
        'confirmed' => 'Confirmado',
        'preparing' => 'Preparando',
        'ready' => 'Listo',
        'completed' => 'Completado',
        'cancelled' => 'Cancelado',
        'orders_list' => 'Lista de Pedidos',
        'all_statuses' => 'Todos los estados',
        'filter_by_date' => 'Filtrar por fecha',
        'search_orders' => 'Buscar pedidos...',
        'filter' => 'Filtrar',
        'order' => 'Pedido',
        'customer' => 'Cliente',
        'pickup' => 'Recoger',
        'total' => 'Total',
        'status' => 'Estado',
        'payment' => 'Pago',
        'date' => 'Fecha',
        'actions' => 'Acciones',
        'items' => 'items',
        'view' => 'Ver',
        'change_status' => 'Cambiar Estado',
        'confirm' => 'Confirmar',
        'order_details' => 'Detalles del Pedido',
        'customer_information' => 'Información del Cliente',
        'order_information' => 'Información del Pedido',
        'name' => 'Nombre',
        'email' => 'Correo',
        'phone' => 'Teléfono',
        'pickup_time' => 'Hora de Recogida',
        'payment_status' => 'Estado de Pago',
        'payment_method' => 'Método de Pago',
        'paid' => 'Pagado',
        'unpaid' => 'No Pagado',
        'cash' => 'Efectivo',
        'card' => 'Tarjeta',
        'online' => 'En Línea',
        'paypal' => 'PayPal',
        'payment_details' => 'Detalles del Pago',
        'order_items' => 'Artículos del Pedido',
        'quantity' => 'Cantidad',
        'subtotal' => 'Subtotal',
        'customizations' => 'Personalizaciones',
        'special_instructions' => 'Instrucciones Especiales',
        'order_total' => 'Total del Pedido',
        'mark_as_paid' => 'Marcar como Pagado',
        'print_order' => 'Imprimir Pedido',
        'back_to_orders' => 'Volver a Pedidos',
        'select_payment_method' => 'Seleccionar método de pago',
        'payment_amount' => 'Cantidad del Pago',
        'payment_notes' => 'Notas del Pago (Opcional)',
        'add_payment_notes' => 'Agregar notas del pago...',
        'mark_as_paid_button' => 'Marcar como Pagado',
        'order_status' => 'Estado del Pedido',
        'current_status' => 'Estado Actual',
        'method' => 'Método',
        'order_number' => 'Número de Pedido',
        'item' => 'Artículo',
        'unit_price' => 'Precio Unitario',
        'extras' => 'Extras',
        'spice_level' => 'Nivel de Picante',
        'thank_you_order' => '¡Gracias por tu pedido!',
        'mark_order_as_paid' => 'Marcar Pedido como Pagado',
        'notes_optional' => 'Notas (Opcional)',
        'change_order_status_confirm' => '¿Cambiar el estado del pedido a',
        'please_select_payment_method' => 'Por favor selecciona un método de pago',
        'please_enter_valid_amount' => 'Por favor ingresa un monto válido',
        'mark_order_paid_confirm' => 'Marcar pedido',
        'as_paid_with' => 'como pagado con',
        'for' => 'por',
        // Categories Management
        'categories_management' => 'Gestión de Categorías',
        'add_category' => 'Agregar Categoría',
        'categories_list' => 'Lista de Categorías',
        'search_categories' => 'Buscar categorías...',
        'name_en' => 'Nombre (EN)',
        'name_es' => 'Nombre (ES)',
        'description' => 'Descripción',
        'products' => 'Productos',
        'created' => 'Creado',
        'edit' => 'Editar',
        'deactivate' => 'Desactivar',
        'activate' => 'Activar',
        'delete' => 'Eliminar',
        'create_new_category' => 'Crear Nueva Categoría',
        'edit_category' => 'Editar Categoría',
        'name_english_required' => 'Nombre (Inglés) *',
        'name_spanish_required' => 'Nombre (Español) *',
        'description_english' => 'Descripción (Inglés)',
        'description_spanish' => 'Descripción (Español)',
        'icon_class' => 'Clase de Icono',
        'color' => 'Color',
        'category_image' => 'Imagen de Categoría',
        'active_category' => 'Categoría Activa',
        'back_to_categories' => 'Volver a Categorías',
        'create_category' => 'Crear Categoría',
        'update_category' => 'Actualizar Categoría',
        'category_information' => 'Información de Categoría',
        'categories_help' => 'Las categorías ayudan a organizar tus productos y facilitan que los clientes encuentren lo que buscan.',
        'tips' => 'Consejos',
        'use_descriptive_names' => 'Usa nombres descriptivos en ambos idiomas',
        'choose_appropriate_icons' => 'Elige iconos y colores apropiados',
        'keep_descriptions_concise' => 'Mantén las descripciones concisas pero informativas',
        'upload_high_quality_images' => 'Sube imágenes de alta calidad para mejor presentación',
        'category_stats' => 'Estadísticas de Categoría',
        'updated' => 'Actualizado',
        'never' => 'Nunca',
        // Dashboard
        'dashboard' => 'Dashboard',
        'orders_today' => 'Órdenes Hoy',
        'revenue_today' => 'Ingresos Hoy',
        'pending_orders' => 'Órdenes Pendientes',
        'pending_reviews' => 'Reseñas Pendientes',
        'orders_by_day' => 'Órdenes por Día (Últimos 7 días)',
        'payment_methods' => 'Métodos de Pago',
        'recent_orders' => 'Órdenes Recientes',
        'view_all' => 'Ver Todas',
        'top_products' => 'Productos Más Vendidos',
        'view_all_products' => 'Ver Todos',
        'sold' => 'vendidos',
        'updating' => 'Actualizando...',
        // Reviews Management
        'reviews_management' => 'Gestión de Reseñas',
        'reviews_list' => 'Lista de Reseñas',
        'search_reviews' => 'Buscar reseñas...',
        'rating' => 'Calificación',
        'comment' => 'Comentario',
        'approved' => 'Aprobado',
        'rejected' => 'Rechazado',
        'review_details' => 'Detalles de la Reseña',
        'review_information' => 'Información de la Reseña',
        'review_comment' => 'Comentario de la Reseña',
        'approve_review' => 'Aprobar Reseña',
        'reject_review' => 'Rechazar Reseña',
        'delete_review' => 'Eliminar Reseña',
        'this_review_already' => 'Esta reseña ya ha sido',
        'approve_review_confirm' => '¿Estás seguro de que quieres aprobar esta reseña?',
        'reject_review_confirm' => '¿Estás seguro de que quieres rechazar esta reseña?',
        'delete_review_confirm' => '¿Estás seguro de que quieres eliminar esta reseña?',
        'reviews' => 'reseñas',
        'per_page' => 'por página',
        'delete_review' => 'Eliminar Reseña',
        'review_details' => 'Detalles de la Reseña',
        'customer_review' => 'Reseña del Cliente',
        'review_date' => 'Fecha de Reseña',
        'review_status' => 'Estado de Reseña',
        'review_comment' => 'Comentario de Reseña',
        'back_to_reviews' => 'Volver a Reseñas',
        // Users Management
        'users_management' => 'Gestión de Usuarios',
        'users_list' => 'Lista de Usuarios',
        'search_users' => 'Buscar usuarios...',
        'administrators' => 'Administradores',
        'active_users' => 'Usuarios Activos',
        'total_users' => 'Total de Usuarios',
        'all_roles' => 'Todos los roles',
        'administrator' => 'Administrador',
        'username' => 'Usuario',
        'role' => 'Rol',
        'last_login' => 'Último Acceso',
        'create_user' => 'Crear Usuario',
        'edit_user' => 'Editar Usuario',
        'create_new_user' => 'Crear Nuevo Usuario',
        'first_name' => 'Nombre',
        'last_name' => 'Apellido',
        'select_role' => 'Seleccionar rol',
        'leave_blank_to_keep_current' => 'dejar en blanco para mantener actual',
        'active_user' => 'Usuario Activo',
        'back_to_users' => 'Volver a Usuarios',
        'update_user' => 'Actualizar Usuario',
        'deactivate' => 'Desactivar',
        'activate' => 'Activar',
        'user_information' => 'Información del Usuario',
        'back_to_users' => 'Volver a Usuarios',
        // Settings
        'settings' => 'Configuración',
        'general_settings' => 'Configuración General',
        'restaurant_info' => 'Información del Restaurante',
        'payment_settings' => 'Configuración de Pagos',
        'email_settings' => 'Configuración de Email',
        'security' => 'Seguridad',
        'social_media' => 'Redes Sociales',
        'settings_menu' => 'Menú de Configuración',
        'save_all' => 'Guardar Todo',
        'site_name' => 'Nombre del Sitio',
        'site_url' => 'URL del Sitio',
        'default_language' => 'Idioma por Defecto',
        'timezone' => 'Zona Horaria',
        'site_description' => 'Descripción del Sitio',
        'site_keywords' => 'Palabras Clave del Sitio',
        'spanish' => 'Español',
        'english' => 'Inglés',
        'pacific_time' => 'Hora del Pacífico (Los Ángeles)',
        'eastern_time' => 'Hora del Este (Nueva York)',
        'central_time' => 'Hora Central (Chicago)',
        'mountain_time' => 'Hora de la Montaña (Denver)',
        'business_hours' => 'Horarios de Atención',
        'monday_to_friday' => 'Lunes a Viernes',
        'saturday' => 'Sábado',
        'sunday' => 'Domingo',
        'closed' => 'Cerrado',
        // Reports
        'reports_analytics' => 'Reportes y Análisis',
        'export' => 'Exportar',
        'report_type' => 'Tipo de Reporte',
        'dashboard_overview' => 'Resumen del Dashboard',
        'sales_report' => 'Reporte de Ventas',
        'orders_report' => 'Reporte de Pedidos',
        'products_report' => 'Reporte de Productos',
        'customers_report' => 'Reporte de Clientes',
        'from_date' => 'Fecha Desde',
        'to_date' => 'Fecha Hasta',
        'generate_report' => 'Generar Reporte',
        'total_revenue' => 'Ingresos Totales',
        // QR Scanner
        'qr_scanner' => 'Escáner QR',
        'scan_qr_code' => 'Escanear Código QR',
        'click_start_scanner' => 'Haz clic en "Iniciar Escáner" para comenzar',
        'search_by_order_number' => 'Buscar por Número de Pedido o ID',
        'enter_order_number_placeholder' => 'Ingresa el número de pedido (ej: HOR202510264726) o ID',
        'search_order' => 'Buscar Pedido',
        'order_search_help' => 'Puedes ingresar el número de pedido (como HOR202510264726) o el ID numérico del pedido',
        'start_scanner' => 'Iniciar Escáner',
        'stop_scanner' => 'Detener Escáner',
        'ready_to_scan' => 'Listo para escanear código QR',
        // Profile
        'my_profile' => 'Mi Perfil',
        'personal_information' => 'Información Personal',
        'phone' => 'Teléfono',
        'cancel' => 'Cancelar',
        'save_changes' => 'Guardar Cambios',
        'back_to_dashboard' => 'Volver al Dashboard',
        // Login
        'please_complete_all_fields' => 'Por favor, completa todos los campos',
        'incorrect_username_password' => 'Usuario o contraseña incorrectos',
        'enter_username' => 'Ingresa tu usuario',
        'enter_password' => 'Ingresa tu contraseña',
        'login' => 'Iniciar Sesión',
        'restricted_access' => 'Acceso restringido al personal autorizado',
        // Extras
        'extra_created_successfully' => 'Extra creado exitosamente',
        'extra_updated_successfully' => 'Extra actualizado exitosamente',
        'extra_deleted_successfully' => 'Extra eliminado exitosamente',
        'extra_assigned_to_product' => 'Extra asignado al producto',
        'extra_removed_from_product' => 'Extra removido del producto',
        'invalid_action' => 'Acción no válida',
        'paypal_client_id' => 'PayPal Client ID',
        'paypal_client_secret' => 'PayPal Client Secret',
        'paypal_mode' => 'Modo PayPal',
        'sandbox' => 'Sandbox',
        'live' => 'Live',
        'smtp_host' => 'SMTP Host',
        'smtp_port' => 'SMTP Puerto',
        'smtp_username' => 'SMTP Usuario',
        'smtp_password' => 'SMTP Contraseña',
        'smtp_encryption' => 'SMTP Encriptación',
        'session_timeout' => 'Tiempo de Sesión',
        'max_login_attempts' => 'Máximo Intentos de Login',
        'facebook_url' => 'URL de Facebook',
        'instagram_url' => 'URL de Instagram',
        'twitter_url' => 'URL de Twitter',
        'youtube_url' => 'URL de YouTube',
        'yelp_url' => 'URL de Yelp',
        'save_changes' => 'Guardar Cambios',
        'changes_saved' => 'Cambios Guardados',
        'error_saving' => 'Error al Guardar',
        // QR Scanner
        'qr_scanner' => 'QR Scanner',
        'scan_qr_code' => 'Escanear Código QR',
        'scan_order_qr' => 'Escanear QR de Pedido',
        'camera_not_available' => 'Cámara no disponible',
        'scan_result' => 'Resultado del Escaneo',
        'order_found' => 'Pedido Encontrado',
        'order_not_found' => 'Pedido No Encontrado',
        'search_by_order_number' => 'Buscar por Número de Pedido',
        'enter_order_number' => 'Ingresar número de pedido',
        'search' => 'Buscar',
        // Reports
        'reports' => 'Reportes',
        'sales_report' => 'Reporte de Ventas',
        'orders_report' => 'Reporte de Pedidos',
        'products_report' => 'Reporte de Productos',
        'customers_report' => 'Reporte de Clientes',
        'date_range' => 'Rango de Fechas',
        'from_date' => 'Desde Fecha',
        'to_date' => 'Hasta Fecha',
        'generate_report' => 'Generar Reporte',
        'export_csv' => 'Exportar CSV',
        'export_pdf' => 'Exportar PDF',
        'total_sales' => 'Ventas Totales',
        'total_orders' => 'Pedidos Totales',
        'average_order_value' => 'Valor Promedio del Pedido',
        'top_selling_products' => 'Productos Más Vendidos',
        'sales_by_day' => 'Ventas por Día',
        'sales_by_month' => 'Ventas por Mes',
        'customer_statistics' => 'Estadísticas de Clientes',
        'new_customers' => 'Nuevos Clientes',
        'returning_customers' => 'Clientes Recurrentes',
        // Common
        'active' => 'Activo',
        'inactive' => 'Inactivo',
        'yes' => 'Sí',
        'no' => 'No',
        'save' => 'Guardar',
        'loading' => 'Cargando...',
        'error' => 'Error',
        'success' => 'Éxito',
        'warning' => 'Advertencia',
        'info' => 'Información',
        'confirm_action' => 'Confirmar Acción',
        'are_you_sure' => '¿Estás seguro?',
        'pay_on_pickup' => 'Pagar al Recoger',
        'number' => 'Número',
        'product' => 'Producto',
        'instructions' => 'Instrucciones',
        'spice_level' => 'Nivel de Picante',
        'none' => 'Ninguno',
        'tax' => 'Impuesto',
        'connection_error' => 'Error de conexión',
        'server_error' => 'Error del servidor',
        'invalid_data' => 'Datos inválidos',
        'required_field' => 'Campo requerido',
        'optional' => 'Opcional',
        'back' => 'Atrás',
        'next' => 'Siguiente',
        'previous' => 'Anterior',
        'first' => 'Primero',
        'last' => 'Último',
        'showing' => 'Mostrando',
        'to' => 'a',
        'of' => 'de',
        'entries' => 'entradas',
        'no_data_available' => 'No hay datos disponibles',
        'no_records_found' => 'No se encontraron registros',
        'search_results' => 'Resultados de búsqueda',
        'filtered_from' => 'filtrado de',
        'total_entries' => 'entradas totales'
    ];
    
    // Textos en inglés
    $texts_en = [
        'home' => 'Home',
        'menu' => 'Menu',
        'reviews' => 'Reviews',
        'contact' => 'Contact',
        'cart' => 'Cart',
        'language' => 'Language',
        'spanish' => 'Español',
        'english' => 'English',
        'welcome' => 'Welcome to Horchata Mexican Food',
        'authentic_mexican' => 'Authentic Mexican Food',
        'our_specialties' => 'Our Specialties',
        'our_categories' => 'Our Categories',
        'customer_reviews' => 'Customer Reviews',
        'contact_info' => 'Contact Information',
        'business_hours' => 'Business Hours',
        'address' => 'Address',
        'phone' => 'Phone',
        'email' => 'Email',
        'monday_saturday' => 'Monday - Saturday',
        'sunday' => 'Sunday',
        'add_to_cart' => 'Add to Cart',
        'view_menu' => 'View Menu',
        'read_reviews' => 'Read Reviews',
        'contact_us' => 'Contact Us',
        'order_now' => 'Order Now',
        'learn_more' => 'Learn More',
        'get_directions' => 'Get Directions',
        'call_now' => 'Call Now',
        'send_message' => 'Send Message',
        'follow_us' => 'Follow Us',
        'all_rights_reserved' => 'All rights reserved',
        'terms_conditions' => 'Terms and Conditions',
        'privacy_policy' => 'Privacy Policy',
        'accessibility' => 'Accessibility',
        // Hero Section
        'authentic_cooking' => 'Authentic Mexican Cooking',
        'flavors_conquer' => 'Flavors that <span class="text-primary-custom">Conquer</span> the Heart',
        'discover_magic' => 'Discover the magic of traditional Mexican cuisine with fresh ingredients, authentic recipes and the flavor that only Horchata Mexican Food can offer you.',
        'years' => 'Years',
        'clients' => 'Clients',
        'dishes' => 'Dishes',
        'explore_menu' => 'Explore Menu',
        'specialties' => 'Specialties',
        'spicy' => 'Spicy',
        'fresh' => 'Fresh',
        'made_with_love' => 'Made with Love',
        // About Section
        'our_story' => 'Our Story',
        'since_2015' => 'Since 2015, Horchata Mexican Food has been the home of authentic Mexican cuisine in our community.',
        'fresh_ingredients' => 'We use fresh ingredients and traditional recipes that have been passed down from generation to generation. Each dish is prepared with love and dedication to give you a unique culinary experience.',
        'years_experience' => 'Years of experience',
        'satisfied_clients' => 'Satisfied clients',
        // Categories Section
        'categories' => 'Categories',
        'explore_variety' => 'Explore the variety of authentic flavors we have to offer you',
        // Reviews Section
        'testimonials' => 'Testimonials',
        'what_customers_say' => 'What Our Customers Say',
        'verified_reviews' => 'Verified reviews from customers who have enjoyed our authentic dishes',
        'see_all_reviews' => 'See All Reviews',
        // Contact Section
        'contact_us_title' => 'Contact Us',
        'we_are_here' => 'We are here to serve you. Visit us or place your order!',
        'location' => 'Location',
        'hours' => 'Hours',
        'phone_number' => '+1 (310) 204-2659',
        'address_full' => '10814 Jefferson Blvd<br>Culver City, CA',
        'hours_full' => 'Mon-Sat: 8:30 AM - 9:00 PM<br>Sunday: 9:00 AM - 8:00 PM',
        // Loading texts
        'loading_specialties' => 'Preparing the best flavors for you',
        'loading_categories' => 'Organizing our flavors for you',
        'loading_testimonials' => 'Collecting the best experiences',
        'explore_full_menu' => 'Explore Full Menu',
        // Menu Page
        'our_menu' => 'Our Menu',
        'discover_authentic' => 'Discover authentic Mexican cuisine with our traditional dishes, prepared with fresh ingredients and family recipes.',
        'all_categories' => 'All',
        'search_dishes' => 'Search dishes...',
        'preparing_menu' => 'Preparing your menu...',
        'loading_delicious' => 'Loading our delicious dishes',
        'oops_not_found' => 'Oops! We didn\'t find that dish',
        'no_dishes_found' => 'No dishes were found with those terms. Try other ingredients or explore our categories.',
        'clear_search' => 'Clear Search',
        'view_all_categories' => 'View All Categories',
        'spicy_dishes' => 'Spicy Dishes',
        'spicy_description' => 'Our spiciest dishes for chili lovers',
        'fresh_ingredients_title' => 'Fresh Ingredients',
        'fresh_ingredients_description' => 'We use only the freshest and highest quality ingredients',
        'made_with_love_title' => 'Made with Love',
        'made_with_love_description' => 'Each dish is prepared with the love of our family recipes',
        // Additional translations
        'popular_dishes_description' => 'The most popular dishes from our menu, prepared with love and Mexican tradition',
        'footer_description' => 'Authentic Mexican food prepared with fresh ingredients and traditional recipes. Enjoy our unique flavors with pickup service.',
        'quick_links' => 'Quick Links',
        'contact_info' => 'Contact Information',
        'business_hours' => 'Business Hours',
        'monday_saturday' => 'Monday - Saturday',
        'sunday' => 'Sunday',
        'all_rights_reserved' => 'All rights reserved',
        'terms_conditions' => 'Terms and Conditions',
        'accessibility' => 'Accessibility',
        'your_cart' => 'Your Cart',
        'cart_empty' => 'Your cart is empty',
        'total' => 'Total',
        'proceed_payment' => 'Proceed to Payment',
        // Reviews Public Page
        'what_customers_say_reviews' => 'What Our Customers Say',
        'discover_authentic_experiences' => 'Discover the authentic experiences of our customers and join the community of lovers of traditional Mexican food.',
        'site_reviews' => 'Site Reviews',
        'yelp_reviews' => 'Yelp Reviews',
        'loading_reviews' => 'Loading reviews...',
        'collecting_best_experiences' => 'Collecting the best experiences',
        'yelp_reviews_title' => 'Yelp Reviews',
        'see_all_yelp_reviews' => 'See all our reviews and ratings on Yelp',
        'yelp_widget' => 'Yelp Widget',
        'yelp_widget_description' => 'The official Yelp widget with the most recent reviews will be displayed here.',
        'view_on_yelp' => 'View on Yelp',
        'load_widget' => 'Load Widget',
        'average_rating' => 'Average Rating',
        'total_reviews' => 'Total Reviews',
        'satisfied_customers' => 'Satisfied Customers',
        'happy_customers' => 'Happy Customers',
        'share_experience' => 'Have an Experience to Share?',
        'share_experience_description' => 'If you have visited our restaurant, we would love to know your opinion. Your feedback helps us improve and better serve our community.',
        'review_on_yelp' => 'Review on Yelp',
        'contact_us' => 'Contact Us',
        // Terms and Conditions Page
        'terms_conditions_title' => 'Terms and Conditions',
        'terms_intro' => 'The Horchata Mexican Food website is for informational purposes only and does not conduct online sales. All intellectual property rights are protected, and we are not responsible for any errors in the information published.',
        'website_use' => 'Use of the Website',
        'website_use_description' => 'This site is for informational purposes only. We do not accept online orders or conduct sales through this platform.',
        'intellectual_property' => 'Intellectual Property',
        'intellectual_property_description' => 'All content on this site, including text, images, and logos, is the property of Horchata Mexican Food.',
        'disclaimer' => 'Disclaimer of Liability',
        'disclaimer_description' => 'Horchata Mexican Food is not responsible for errors in the information on the site or for damages arising from its use.',
        'contact_information' => 'Contact Information',
        // Accessibility Page
        'accessibility_title' => 'WCAG Accessibility',
        'accessibility_intro' => 'Horchata Mexican Food is committed to making its website accessible to all people, including those with disabilities.',
        'our_commitment' => 'Our Commitment',
        'our_commitment_description' => 'We believe that web accessibility is fundamental to creating an inclusive experience for all our visitors. We strive to comply with web accessibility guidelines (WCAG) to ensure our site is usable by people with diverse abilities.',
        'measures_implemented' => 'Measures Implemented',
        'adequate_color_contrast' => 'Adequate Color Contrasts',
        'adequate_color_contrast_description' => 'We use color combinations that meet WCAG AA contrast standards to ensure readability.',
        'alt_text_images' => 'Text Alternatives for Images',
        'alt_text_images_description' => 'All images include alternative descriptions (alt text) for screen reader users.',
        'screen_reader_navigation' => 'Screen Reader-Friendly Navigation',
        'screen_reader_navigation_description' => 'Our site is structured to be completely navigable using assistive technologies.',
        'responsive_design' => 'Responsive Design',
        'responsive_design_description' => 'The site adapts to different screen sizes and devices for an optimal experience.',
        'additional_features' => 'Additional Features',
        'semantic_html5' => 'Semantic HTML5 structure for better navigation',
        'descriptive_links' => 'Descriptive and clear links',
        'accessible_forms' => 'Accessible forms with appropriate labels',
        'keyboard_navigation' => 'Complete keyboard navigation',
        'scalable_text' => 'Scalable text without loss of functionality',
        'hierarchical_content' => 'Hierarchically organized content',
        'report_accessibility_issues' => 'Report Accessibility Issues',
        'report_accessibility_description' => 'If you experience difficulties accessing any part of our website, or if you have suggestions to improve accessibility, please contact us:',
        // Product Detail Page
        'quantity' => 'Quantity',
        'ingredients' => 'Ingredients',
        'nutritional_information' => 'Nutritional Information',
        'preparation_time' => 'Preparation time',
        'spicy_level' => 'Spicy level',
        'preparation_time_default' => 'Preparation time: 15-20 min',
        'spicy_level_default' => 'Spicy level: Medium',
        'traditional_recipe' => 'Traditional recipe',
        'ingredients_description' => 'Fresh ingredients carefully selected to ensure the best quality and authentic flavor.',
        'fresh_ingredients_list_1' => 'Premium beef',
        'fresh_ingredients_list_2' => 'Fresh onion and garlic',
        'fresh_ingredients_list_3' => 'Traditional spices',
        'fresh_ingredients_list_4' => 'Corn tortillas',
        'nutritional_info_default' => 'Detailed nutritional information is not available for this product.',
        'favorites' => 'Favorites',
        'related_products' => 'Related Products',
        'related_products_description' => 'Other dishes from the same category that might interest you',
        'view' => 'View',
        // Customize Modal
        'customize_order' => 'Customize Order',
        'special_instructions' => 'Special Instructions',
        'special_instructions_placeholder' => 'E.g., No onion, no tomatoes, no cilantro...',
        'special_instructions_help' => 'Add any special instructions for your order',
        'extras' => 'Extras',
        'extra_cheese' => 'Extra Cheese',
        'extra_guacamole' => 'Extra Guacamole',
        'extra_sour_cream' => 'Extra Sour Cream',
        'spice_level' => 'Spice Level',
        'mild' => 'Mild',
        'hot' => 'Hot',
        'extra_hot' => 'Extra Hot',
        'cancel' => 'Cancel',
        // Checkout Page
        'finish_order' => 'Finish Order',
        'customer_information' => 'Customer Information',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'email_address' => 'Email Address',
        'phone_number' => 'Phone Number',
        'pickup_information' => 'Pickup Information',
        'pickup_date' => 'Pickup Date',
        'pickup_time' => 'Pickup Time',
        'select_time' => 'Select time',
        'allergies_modifications' => 'Allergies, modifications, etc.',
        'payment_method' => 'Payment Method',
        'pay_safely_paypal' => 'Pay securely with PayPal',
        'pay_on_pickup' => 'Pay on Pickup',
        'cash_card_paypal_pickup' => 'Cash, card, or PayPal when picking up',
        'order_summary' => 'Order Summary',
        'quantity' => 'Quantity',
        'subtotal' => 'Subtotal',
        'tax' => 'Tax',
        'tax_percentage' => 'Tax (8.25%)',
        'total' => 'Total',
        'confirm_order' => 'Confirm Order',
        'ssl_protected' => 'Your information is protected with SSL encryption',
        'processing' => 'Processing...',
        'complete_all_fields' => 'Please complete all required fields',
        'please_complete_required_fields' => 'Please complete all required fields',
        'complete_customer_and_pickup_info' => 'Complete customer information and pickup information before proceeding to payment',
        'error_processing_order' => 'Error processing order: ',
        // Wire Transfer
        'wire_transfer' => 'Wire Transfer',
        'wire_transfer_description' => 'Send a direct bank wire transfer',
        'wire_transfer_information' => 'Wire Transfer Information',
        'bank_name' => 'Bank Name',
        'account_holder' => 'Account Holder',
        'account_number' => 'Account Number',
        'routing_number_wire' => 'Routing Number (Wire Transfer)',
        'routing_number_direct_deposit' => 'Routing Number (Direct Deposit)',
        'swift_code' => 'SWIFT Code',
        'wire_transfer_instructions' => 'Instructions',
        'for_direct_deposit' => 'For direct deposits',
        'for_international_wires' => 'For international wires',
        'wire_transfer_note' => 'Please include the order number in the transfer description to facilitate identification.',
        'important' => 'Important',
        // Order Success Page
        'order_confirmed' => 'Order Confirmed',
        'order_confirmed_message' => 'Thank you for your order. We have sent you a confirmation email with all the details.',
        'order_details' => 'Order Details',
        'order_number' => 'Order Number',
        'order_date' => 'Order Date',
        'order_items' => 'Order Items',
        'payment_information' => 'Payment Information',
        'payment_method' => 'Payment Method',
        'payment_status' => 'Payment Status',
        'pay_on_pickup' => 'Pay on Pickup',
        'contact_information' => 'Contact Information',
        'phone' => 'Phone',
        'email' => 'Email',
        'address' => 'Address',
        'back_to_home' => 'Back to Home',
        'view_menu' => 'View Menu',
        'print_order' => 'Print Order',
        'leave_review' => 'Leave a Review',
        'leave_review_message' => 'We would love to hear about your experience! Leave a review and help other customers.',
        'write_review' => 'Write Review',
        // Review Form
        'rating' => 'Rating',
        'select_rating' => 'Select a rating',
        'stars' => 'stars',
        'star' => 'star',
        'your_review' => 'Your Review',
        'write_your_review_here' => 'Write your review here...',
        'submit_review' => 'Submit Review',
        // Review error messages
        'error_loading_reviews' => 'Error loading reviews',
        'error_loading_public_reviews' => 'Error loading public reviews',
        'try_again' => 'Try again',
        // Additional order success translations
        'qr_code_for_restaurant' => 'QR Code for Restaurant',
        'scan_qr_to_view_order' => 'Scan this code to view the order in the system',
        'customer' => 'Customer',
        'status' => 'Status',
        'subtotal' => 'Subtotal',
        'tax' => 'Tax',
        'quantity' => 'Quantity',
        // Product customization extras
        'guacamole' => 'Guacamole',
        'sour_cream' => 'Sour Cream',
        'cheese' => 'Cheese',
        // Extras Management
        'extras_management' => 'Extras Management',
        'add_extra' => 'Add Extra',
        'edit_extra' => 'Edit Extra',
        'extras_list' => 'Extras List',
        'assign_extras_to_products' => 'Assign Extras to Products',
        'select_product' => 'Select Product',
        'available_extras' => 'Available Extras',
        'select_product_first' => 'Select a product first',
        'no_category' => 'No category',
        'confirm_delete_extra' => 'Are you sure you want to delete this extra?',
        // Admin Panel
        'dashboard' => 'Dashboard',
        'products' => 'Products',
        'orders' => 'Orders',
        'qr_scanner' => 'QR Scanner',
        'reports' => 'Reports',
        'categories' => 'Categories',
        'extras' => 'Extras',
        'users' => 'Users',
        'profile' => 'Profile',
        'view_site' => 'View Site',
        'logout' => 'Logout',
        // Product Management
        'new_product' => 'New Product',
        'edit_product' => 'Edit Product',
        'name_english' => 'Name (English)',
        'name_spanish' => 'Name (Spanish)',
        'category' => 'Category',
        'select_category' => 'Select category',
        'price' => 'Price',
        'description_english' => 'Description (English)',
        'description_spanish' => 'Description (Spanish)',
        'available' => 'Available',
        'featured' => 'Featured',
        'product_image' => 'Product Image',
        'preview' => 'Preview',
        'image_formats' => 'Formats: JPG, PNG, GIF. Max 5MB',
        'product_extras' => 'Product Extras',
        'available_extras' => 'Available Extras',
        'assigned_extras' => 'Assigned Extras',
        'loading_extras' => 'Loading extras',
        'loading_assigned_extras' => 'Loading assigned extras',
        'add_new_extra' => 'Add New Extra',
        'cancel' => 'Cancel',
        'create_product' => 'Create Product',
        'update_product' => 'Update Product',
        // Order Management
        'order_management' => 'Order Management',
        'refresh' => 'Refresh',
        'print' => 'Print',
        'pending' => 'Pending',
        'confirmed' => 'Confirmed',
        'preparing' => 'Preparing',
        'ready' => 'Ready',
        'completed' => 'Completed',
        'cancelled' => 'Cancelled',
        'orders_list' => 'Orders List',
        'all_statuses' => 'All statuses',
        'filter_by_date' => 'Filter by date',
        'search_orders' => 'Search orders...',
        'filter' => 'Filter',
        'order' => 'Order',
        'customer' => 'Customer',
        'pickup' => 'Pickup',
        'total' => 'Total',
        'status' => 'Status',
        'payment' => 'Payment',
        'date' => 'Date',
        'actions' => 'Actions',
        'items' => 'items',
        'view' => 'View',
        'change_status' => 'Change Status',
        'confirm' => 'Confirm',
        'order_details' => 'Order Details',
        'customer_information' => 'Customer Information',
        'order_information' => 'Order Information',
        'name' => 'Name',
        'email' => 'Email',
        'phone' => 'Phone',
        'pickup_time' => 'Pickup Time',
        'payment_status' => 'Payment Status',
        'payment_method' => 'Payment Method',
        'paid' => 'Paid',
        'unpaid' => 'Unpaid',
        'cash' => 'Cash',
        'card' => 'Card',
        'online' => 'Online',
        'paypal' => 'PayPal',
        'payment_details' => 'Payment Details',
        'order_items' => 'Order Items',
        'quantity' => 'Quantity',
        'subtotal' => 'Subtotal',
        'customizations' => 'Customizations',
        'special_instructions' => 'Special Instructions',
        'order_total' => 'Order Total',
        'mark_as_paid' => 'Mark as Paid',
        'print_order' => 'Print Order',
        'back_to_orders' => 'Back to Orders',
        'select_payment_method' => 'Select payment method',
        'payment_amount' => 'Payment Amount',
        'payment_notes' => 'Payment Notes (Optional)',
        'add_payment_notes' => 'Add payment notes...',
        'mark_as_paid_button' => 'Mark as Paid',
        'order_status' => 'Order Status',
        'current_status' => 'Current Status',
        'method' => 'Method',
        'order_number' => 'Order Number',
        'item' => 'Item',
        'unit_price' => 'Unit Price',
        'extras' => 'Extras',
        'spice_level' => 'Spice Level',
        'thank_you_order' => 'Thank you for your order!',
        'mark_order_as_paid' => 'Mark Order as Paid',
        'notes_optional' => 'Notes (Optional)',
        'change_order_status_confirm' => 'Change order status to',
        'please_select_payment_method' => 'Please select a payment method',
        'please_enter_valid_amount' => 'Please enter a valid payment amount',
        'mark_order_paid_confirm' => 'Mark order',
        'as_paid_with' => 'as paid with',
        'for' => 'for',
        // Categories Management
        'categories_management' => 'Categories Management',
        'add_category' => 'Add Category',
        'categories_list' => 'Categories List',
        'search_categories' => 'Search categories...',
        'name_en' => 'Name (EN)',
        'name_es' => 'Name (ES)',
        'description' => 'Description',
        'products' => 'Products',
        'created' => 'Created',
        'edit' => 'Edit',
        'deactivate' => 'Deactivate',
        'activate' => 'Activate',
        'delete' => 'Delete',
        'create_new_category' => 'Create New Category',
        'edit_category' => 'Edit Category',
        'name_english_required' => 'Name (English) *',
        'name_spanish_required' => 'Name (Spanish) *',
        'description_english' => 'Description (English)',
        'description_spanish' => 'Description (Spanish)',
        'icon_class' => 'Icon Class',
        'color' => 'Color',
        'category_image' => 'Category Image',
        'active_category' => 'Active Category',
        'back_to_categories' => 'Back to Categories',
        'create_category' => 'Create Category',
        'update_category' => 'Update Category',
        'category_information' => 'Category Information',
        'categories_help' => 'Categories help organize your products and make it easier for customers to find what they\'re looking for.',
        'tips' => 'Tips',
        'use_descriptive_names' => 'Use descriptive names in both languages',
        'choose_appropriate_icons' => 'Choose appropriate icons and colors',
        'keep_descriptions_concise' => 'Keep descriptions concise but informative',
        'upload_high_quality_images' => 'Upload high-quality images for better presentation',
        'category_stats' => 'Category Stats',
        'updated' => 'Updated',
        'never' => 'Never',
        // Dashboard
        'dashboard' => 'Dashboard',
        'orders_today' => 'Orders Today',
        'revenue_today' => 'Revenue Today',
        'pending_orders' => 'Pending Orders',
        'pending_reviews' => 'Pending Reviews',
        'orders_by_day' => 'Orders by Day (Last 7 days)',
        'payment_methods' => 'Payment Methods',
        'recent_orders' => 'Recent Orders',
        'view_all' => 'View All',
        'top_products' => 'Top Products',
        'view_all_products' => 'View All',
        'sold' => 'sold',
        'updating' => 'Updating...',
        // Reviews Management
        'reviews_management' => 'Reviews Management',
        'reviews_list' => 'Reviews List',
        'search_reviews' => 'Search reviews...',
        'rating' => 'Rating',
        'comment' => 'Comment',
        'approved' => 'Approved',
        'rejected' => 'Rejected',
        'review_details' => 'Review Details',
        'review_information' => 'Review Information',
        'review_comment' => 'Review Comment',
        'approve_review' => 'Approve Review',
        'reject_review' => 'Reject Review',
        'delete_review' => 'Delete Review',
        'this_review_already' => 'This review has already been',
        'approve_review_confirm' => 'Are you sure you want to approve this review?',
        'reject_review_confirm' => 'Are you sure you want to reject this review?',
        'delete_review_confirm' => 'Are you sure you want to delete this review?',
        'reviews' => 'reviews',
        'per_page' => 'per page',
        'review_comment' => 'Review Comment',
        'back_to_reviews' => 'Back to Reviews',
        // Users Management
        'users_management' => 'Users Management',
        'users_list' => 'Users List',
        'search_users' => 'Search users...',
        'administrators' => 'Administrators',
        'active_users' => 'Active Users',
        'total_users' => 'Total Users',
        'all_roles' => 'All roles',
        'administrator' => 'Administrator',
        'username' => 'Username',
        'role' => 'Role',
        'last_login' => 'Last Login',
        'create_user' => 'Create User',
        'edit_user' => 'Edit User',
        'create_new_user' => 'Create New User',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'select_role' => 'Select role',
        'leave_blank_to_keep_current' => 'leave blank to keep current',
        'active_user' => 'Active User',
        'back_to_users' => 'Back to Users',
        'update_user' => 'Update User',
        'deactivate' => 'Deactivate',
        'activate' => 'Activate',
        // Settings
        'settings' => 'Settings',
        'general_settings' => 'General Settings',
        'restaurant_info' => 'Restaurant Info',
        'payment_settings' => 'Payment Settings',
        'email_settings' => 'Email Settings',
        'security' => 'Security',
        'social_media' => 'Social Media',
        'settings_menu' => 'Settings Menu',
        'save_all' => 'Save All',
        'site_name' => 'Site Name',
        'site_url' => 'Site URL',
        'default_language' => 'Default Language',
        'timezone' => 'Timezone',
        'site_description' => 'Site Description',
        'site_keywords' => 'Site Keywords',
        'spanish' => 'Spanish',
        'english' => 'English',
        'pacific_time' => 'Pacific Time (Los Angeles)',
        'eastern_time' => 'Eastern Time (New York)',
        'central_time' => 'Central Time (Chicago)',
        'mountain_time' => 'Mountain Time (Denver)',
        'business_hours' => 'Business Hours',
        'monday_to_friday' => 'Monday to Friday',
        'saturday' => 'Saturday',
        'sunday' => 'Sunday',
        'closed' => 'Closed',
        // Reports
        'reports_analytics' => 'Reports & Analytics',
        'export' => 'Export',
        'report_type' => 'Report Type',
        'dashboard_overview' => 'Dashboard Overview',
        'sales_report' => 'Sales Report',
        'orders_report' => 'Orders Report',
        'products_report' => 'Products Report',
        'customers_report' => 'Customers Report',
        'from_date' => 'From Date',
        'to_date' => 'To Date',
        'generate_report' => 'Generate Report',
        'total_revenue' => 'Total Revenue',
        // QR Scanner
        'qr_scanner' => 'QR Scanner',
        'scan_qr_code' => 'Scan QR Code',
        'click_start_scanner' => 'Click "Start Scanner" to begin',
        'search_by_order_number' => 'Search by Order Number or ID',
        'enter_order_number_placeholder' => 'Enter order number (e.g., HOR202510264726) or ID',
        'search_order' => 'Search Order',
        'order_search_help' => 'You can enter the order number (like HOR202510264726) or the numeric order ID',
        'start_scanner' => 'Start Scanner',
        'stop_scanner' => 'Stop Scanner',
        'ready_to_scan' => 'Ready to scan QR code',
        // Profile
        'my_profile' => 'My Profile',
        'personal_information' => 'Personal Information',
        'phone' => 'Phone',
        'cancel' => 'Cancel',
        'save_changes' => 'Save Changes',
        'back_to_dashboard' => 'Back to Dashboard',
        // Login
        'please_complete_all_fields' => 'Please complete all fields',
        'incorrect_username_password' => 'Incorrect username or password',
        'enter_username' => 'Enter your username',
        'enter_password' => 'Enter your password',
        'login' => 'Login',
        'restricted_access' => 'Restricted access to authorized personnel only',
        // Extras
        'extra_created_successfully' => 'Extra created successfully',
        'extra_updated_successfully' => 'Extra updated successfully',
        'extra_deleted_successfully' => 'Extra deleted successfully',
        'extra_assigned_to_product' => 'Extra assigned to product',
        'extra_removed_from_product' => 'Extra removed from product',
        'invalid_action' => 'Invalid action',
        'paypal_client_id' => 'PayPal Client ID',
        'paypal_client_secret' => 'PayPal Client Secret',
        'paypal_mode' => 'PayPal Mode',
        'sandbox' => 'Sandbox',
        'live' => 'Live',
        'smtp_host' => 'SMTP Host',
        'smtp_port' => 'SMTP Port',
        'smtp_username' => 'SMTP Username',
        'smtp_password' => 'SMTP Password',
        'smtp_encryption' => 'SMTP Encryption',
        'session_timeout' => 'Session Timeout',
        'max_login_attempts' => 'Max Login Attempts',
        'facebook_url' => 'Facebook URL',
        'instagram_url' => 'Instagram URL',
        'twitter_url' => 'Twitter URL',
        'youtube_url' => 'YouTube URL',
        'yelp_url' => 'Yelp URL',
        'save_changes' => 'Save Changes',
        'changes_saved' => 'Changes Saved',
        'error_saving' => 'Error Saving',
        // QR Scanner
        'qr_scanner' => 'QR Scanner',
        'scan_qr_code' => 'Scan QR Code',
        'scan_order_qr' => 'Scan Order QR',
        'camera_not_available' => 'Camera not available',
        'scan_result' => 'Scan Result',
        'order_found' => 'Order Found',
        'order_not_found' => 'Order Not Found',
        'search_by_order_number' => 'Search by Order Number',
        'enter_order_number' => 'Enter order number',
        'search' => 'Search',
        // Reports
        'reports' => 'Reports',
        'sales_report' => 'Sales Report',
        'orders_report' => 'Orders Report',
        'products_report' => 'Products Report',
        'customers_report' => 'Customers Report',
        'date_range' => 'Date Range',
        'from_date' => 'From Date',
        'to_date' => 'To Date',
        'generate_report' => 'Generate Report',
        'export_csv' => 'Export CSV',
        'export_pdf' => 'Export PDF',
        'total_sales' => 'Total Sales',
        'total_orders' => 'Total Orders',
        'average_order_value' => 'Average Order Value',
        'top_selling_products' => 'Top Selling Products',
        'sales_by_day' => 'Sales by Day',
        'sales_by_month' => 'Sales by Month',
        'customer_statistics' => 'Customer Statistics',
        'new_customers' => 'New Customers',
        'returning_customers' => 'Returning Customers',
        // Common
        'active' => 'Active',
        'inactive' => 'Inactive',
        'yes' => 'Yes',
        'no' => 'No',
        'save' => 'Save',
        'loading' => 'Loading...',
        'error' => 'Error',
        'success' => 'Success',
        'warning' => 'Warning',
        'info' => 'Info',
        'confirm_action' => 'Confirm Action',
        'are_you_sure' => 'Are you sure?',
        'pay_on_pickup' => 'Pay on Pickup',
        'number' => 'Number',
        'product' => 'Product',
        'instructions' => 'Instructions',
        'spice_level' => 'Spice Level',
        'none' => 'None',
        'tax' => 'Tax',
        'connection_error' => 'Connection error',
        'server_error' => 'Server error',
        'invalid_data' => 'Invalid data',
        'required_field' => 'Required field',
        'optional' => 'Optional',
        'back' => 'Back',
        'next' => 'Next',
        'previous' => 'Previous',
        'first' => 'First',
        'last' => 'Last',
        'showing' => 'Showing',
        'to' => 'to',
        'of' => 'of',
        'entries' => 'entries',
        'no_data_available' => 'No data available',
        'no_records_found' => 'No records found',
        'search_results' => 'Search results',
        'filtered_from' => 'filtered from',
        'total_entries' => 'total entries'
    ];
    
    $texts = $lang === 'en' ? $texts_en : $texts_es;
    
    return $texts[$key] ?? $default ?? $key;
}

// Variable global para invalidar caché de settings
$GLOBALS['_settings_cache_invalid'] = false;

/**
 * Invalidar caché de configuraciones
 */
function invalidateSettingsCache() {
    $GLOBALS['_settings_cache_invalid'] = true;
}

/**
 * Obtener configuración del sistema
 */
function getSetting($key, $default = '') {
    static $settings = null;
    static $last_load = null;
    global $pdo;
    
    // Recargar caché si está invalidado, cada 5 minutos, o si es la primera vez
    $cache_invalid = isset($GLOBALS['_settings_cache_invalid']) && $GLOBALS['_settings_cache_invalid'];
    $should_reload = ($settings === null) || ($last_load === null) || $cache_invalid || (time() - $last_load > 300);
    
    // Si las configuraciones no están cargadas o necesitan recargarse
    if ($should_reload) {
        $settings = [];
        
        try {
            // Usar $pdo global si está disponible
            if (isset($pdo) && $pdo instanceof PDO) {
                $sql = "SELECT setting_key, setting_value FROM settings";
                $stmt = $pdo->prepare($sql);
                $stmt->execute();
                $results = $stmt->fetchAll(PDO::FETCH_ASSOC);
                
                foreach ($results as $result) {
                    $settings[$result['setting_key']] = $result['setting_value'];
                }
            } else {
                // Si $pdo no está disponible, intentar cargar db_connect.php
                if (file_exists(__DIR__ . '/db_connect.php')) {
                    require_once __DIR__ . '/db_connect.php';
                    
                    if (isset($pdo) && $pdo instanceof PDO) {
                        $sql = "SELECT setting_key, setting_value FROM settings";
                        $stmt = $pdo->prepare($sql);
                        $stmt->execute();
                        $results = $stmt->fetchAll(PDO::FETCH_ASSOC);
                        
                        foreach ($results as $result) {
                            $settings[$result['setting_key']] = $result['setting_value'];
                        }
                    }
                }
            }
        } catch (Exception $e) {
            error_log("Error loading settings: " . $e->getMessage());
        }
        
        $last_load = time();
        // Resetear invalidación después de recargar
        $GLOBALS['_settings_cache_invalid'] = false;
    }
    
    return $settings[$key] ?? $default;
}
?>
